# Generated by Django 4.2.5 on 2023-09-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups_list',
            old_name='date_star',
            new_name='date_start',
        ),
    ]
