# Generated by Django 4.2.5 on 2023-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_list',
            name='science_degree',
            field=models.CharField(max_length=20),
        ),
    ]
